### ISSUE TITLE
App crash when adding translation while sorting alphabetically

### ISSUE THREAD

**Issue by diogotcorreia** [tritonmc/twin#10]
Steps to reproduce:
1. Visit https://twin.rexcantor64.com/demo
2. Sort translations by alphabetic order
3. Click the + icon and add a new text translation
4. Click x on the top-left corner to close the translation (without editing anything)
5. Repeat step 3
6. You just got a white page

**Comment by BAttomic** [comment]
Thanks for fixing another bug i found!
Awesome plugin, its helping me a lot!
